name: Update NPM Dependencies
description: "Checks if there are updates to NPM packages, and creates a PR with the updated package*.json files"
inputs:
  base-branch:
    description: The branch used as the base for the depedency update checks
    default: main
    required: false
  target-branch:
    description: The branch from which the PR is created
    default: update-Dependencies
    required: false
  working-directory:
    description: The working directory of the project from which check for dependencies
    required: true
  gh-token:
    description: Authentication Token with repository access. Must have write access to contents and pull-requests.
    required: true
  debug:
    description: Whether the output debug messages to the console.
    required: false
runs:
  using: node24
  main: index.js